### ISSUE TITLE
ImportError: cannot import name 'SearchSupervised

### ISSUE THREAD

**Issue by 1beto** [keras-team/autokeras#621]
Hi, 

I tried to use the SearchSupervisor to fit some data, but the output that I got was:

`Traceback (most recent call last):
  File "rico_autokeras.py", line 57, in <module>
    from autokeras import SearchSupervised
ImportError: cannot import name 'SearchSupervised'
`
There is a simple reason for that?

**Comment by gerlaic** [comment]
I think there are two parts of the issue.

1. You can't just do `import SearchSupervised`. SearchSupervised is a sub class of `Supervised` and is not import with `import keras`. You can check here:
https://github.com/keras-team/autokeras/blob/master/autokeras/__init__.py
As you can see the module `supervised.py` is not imported with the `init`

So in order to import SearchSupervised class, you would need to do that yourself by
`import autokeras.supervised.SearchSupervised`

But then here comes the second part

2. If you check the `supervised.py`. You would see that it's full of abstract methods for now. An abstract method is a method that is declared, but contains no implementation.
Abstract classes may not be instantiated, and require subclasses to provide implementations for the abstract methods. And I don't think any of the subclasses is fully implemented.
