### ISSUE TITLE
ERROR: No matching distribution found for torch==1.0.1

### ISSUE THREAD

**Issue by Lay4U** [keras-team/autokeras#694]
``` pip install autokeras ```
then ERROR: No matching distribution found for torch==1.0.1.post2 (from autokeras) occur

and when  ```pip install torch==1.0.1 -f https://download.pytorch.org/whl/cpu/stable```
then ERROR: No matching distribution found for torch==1.0.1 occur

can't use on windows10?

python : 3.6
OS : window10

**Comment by keremgocen** [comment]
There is no easy way to install autokeras on windows unfortunately. Easy way is to just use ubuntu 18.04 and `pip install autokeras` will work.

Otherwise you'll have to get an old release from github, tweak the dependencies in setup.py to something compatible and install it manually using `python setup.py`. I tried it as well, ended up installing ubuntu on another ssd so I can use the GPU of my PC.
