### ISSUE TITLE
i can't run my autokeras scripts

### ISSUE THREAD

**Issue by Kantshun** [keras-team/autokeras#849]
autokeras version:1.0.0a0
windows 10 pro
i got dll error as follow
![image](https://user-images.githubusercontent.com/31396222/70022830-7f385300-15d0-11ea-855b-002942f9393e.png)
i have no idea which dll file is missing. could anybody help me?

**Comment by Elbek1997** [comment]
Do you have CUDA toolkit, and tensorflow-gpu installed?

**Comment by Kantshun** [comment]
I have CUDA toolkit and tensorflow installed. but not sure wethere my tensorflow is gpu version or not.
![image](https://user-images.githubusercontent.com/31396222/70058849-a61b7700-161a-11ea-9d3e-e035d5093158.png)
![image](https://user-images.githubusercontent.com/31396222/70058988-ea0e7c00-161a-11ea-8088-9c4bf8e42bbd.png)

**Comment by Kantshun** [comment]
I'm sure I have tensorflow-gpu installed now,but I still can't run my autokeras script. could anyone help me?
![image](https://user-images.githubusercontent.com/31396222/70108470-5a051c80-1684-11ea-823f-fb9242c61b7d.png)

**Comment by Kantshun** [comment]
I'm sure I have tensorflow-gpu installed now, but still can't run my autokeras scripts. could anyone help me?
![image](https://user-images.githubusercontent.com/31396222/70108551-9173c900-1684-11ea-8eca-a7da96921124.png)

**Comment by gabrieldemarmiesse** [comment]
The error you got is unrelated to cuda, it seems that the install of scikit-learn is broken. I don't know what is the reason though. You can see it by doing:

```python
from sklearn import exceptions
```

And you'll see a similar error. 

I would recommend two things:

1) On windows, use anaconda as your python installation. You'll have far less issues. Use "conda install" to install scikit learn.
2) If the problem persist, ask your questions on stackoverflow or report a bug in the scikit-learn repo, since it's unrelated to autokeras. The core devs here (keras-team in general) have very little time overall, so let's dispatch the problems to their appropriate channels.

I hope you'll fix it quickly! Good luck!
