### ISSUE TITLE
 ImportError: cannot import name 'preprocessing' from 'tensorflow.keras.layers.experimental'

### ISSUE THREAD

**Issue by kevinkit** [keras-team/autokeras#942]
I tried to run Auotokeras and was hit with the error message upon import autokeras:

`
ImportError: cannot import name 'preprocessing' from 'tensorflow.keras.layers.experimental'`

I think this is due to some version mismatch, - so I suggest that the documentation should include the needed tensorlfow / keras versions.

I am currently on:

Keras: 2.2.4
Tensorflow: 1.15.0
OS: Windows 10

Thank you for your help

**Comment by jcrodriguez1989** [comment]
Hi @kevinkit , the minimum tensorflow requirement is 2.1.0 .
It would be great if this requirement could be documented.

**Comment by kevinkit** [comment]
Thank you very much for that information and fast reply - is there a version requirement for Keras, too?

**Comment by haifeng-jin** [comment]
@jcrodriguez1989 Yeah, I will add it to the documentation later today. Thx

@kevinkit We are actually using the tf.keras (Keras inside TensorFlow package) instead of the standalone Keras.
So you don't need to worry about the installation of Keras as long as you installed the correct version of TensorFlow. Thx

**Comment by amir1m** [comment]
I have both requirements satisfied still getting the same error.

Keras: 2.3.1
Tensorflow: 2.0.0
OS: Mac OS Mojave

**Comment by kevinkit** [comment]
It is tensorflow 2.**1**.0 like already sad above

**Comment by amir1m** [comment]
It's working now. Missed the minor version of TF. Thanks for reply!

**Comment by RingoD** [comment]
I have tried both tf 2.1.0 and 2.2.0 still getting the same error.

1. 
![image](https://user-images.githubusercontent.com/2156166/85382004-1cf56e80-b571-11ea-9ac5-5177fc029e78.png)

tf is installed using `docker pull tensorflow/tensorflow:latest-py3`.

2. 
![image](https://user-images.githubusercontent.com/2156166/85382252-57f7a200-b571-11ea-9520-c2fbe87a68be.png)

tf is installed using `pip3 install tensorflow`.

**Comment by imdadulhaque1** [comment]
@kevinkit Thank a lot for making a perfect guideline !

**Comment by parthlathiya42** [comment]
Solved the issue by upgrading tensorflow.

**Comment by AI-07** [comment]
> Hi @kevinkit , the minimum tensorflow requirement is 2.1.0 . It would be great if this requirement could be documented.

Hi @jcrodriguez1989 I'm getting the same error on google colab with tf version 2.8.0. Any idea what could be the reason.

**Comment by nassssro0444** [comment]
> > Hi @kevinkit , the minimum tensorflow requirement is 2.1.0 . It would be great if this requirement could be documented.
> 
> Hi @jcrodriguez1989 I'm getting the same error on google colab with tf version 2.8.0. Any idea what could be the reason?

i'm getting the same error did you find any solution ?

**Comment by haifeng-jin** [comment]
@nassssro0444  @AI-07 
I cannot reproduce this error. My notebook:
https://colab.research.google.com/drive/1vdWhiiwceim6qdvSGwi7O-8A9MOgH8ff?usp=sharing

Would you please provide a bug reproduction notebook?
Thanks.

**Comment by nassssro0444** [comment]
hey bro just add this instruction to your notebook
from tensorflow.keras.preprocessing import preprocess_input the error msg
will be shown here :

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

<ipython-input-1-2569fd104ea5> <https://localhost:8080/#> in <module>()
----> 1 from tensorflow.keras.preprocessing import preprocess_input


ImportError: cannot import name 'preprocess_input' from
'tensorflow.keras.preprocessing'
(/usr/local/lib/python3.7/dist-packages/keras/api/_v2/keras/preprocessing/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------


‫في الأربعاء، 27 أبريل 2022 في 8:23 م تمت كتابة ما يلي بواسطة ‪Haifeng
Jin‬‏ ***@***.***‬‏>:‬

**Comment by haifeng-jin** [comment]
@nassssro0444 
Does this code appear anywhere in autokeras?
How to get this error with autokeras?

**Comment by nassssro0444** [comment]
@haifeng-jin  sorry i didn't undrstund what are u trying to say , but  anything i can do for fix this error ??

**Comment by haifeng-jin** [comment]
@nassssro0444
My question is: the code to reproduce the error only uses tensorflow. It did not use autokeras.
So did you run into this error when you use autokeras?
Would you paste the code of using autokeras to produce this error?
